<?php

/**
 * @file
 *   Mailsystem module install/schema hooks.
 */


function mailsystem_update_1000() {
  $config = config('mailsystem.settings');

  // migrate variables
  $config->set('mail_system', update_variable_get('mail_system'));
  $config->set('mailsystem_theme', update_variable_get('mailsystem_theme'));
  $config->save();

  // Delete variables.
  update_variable_del('mail_system');
  update_variable_del('mailsystem_theme');
}
